# GitHub Actions workflow for a Python application

name: Python application

on:
  push:
    tags: [ "v*.*.*" ]
  # Trigger the workflow on pull requests to main or release branches
  pull_request:
    branches: [ "main", "release/**", "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DISPLAY: ":99.0"
      QT_SELECT: "qt6"

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4
    # Set up Python 3.12
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils libgl1 libegl1 libdbus-1-3 libxkbcommon0 xvfb

    - uses: tlambert03/setup-qt-libs@v1
    - name: build "display"
      run: |
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install keyrings.alt
        pip install -e .

    - name: Lint with flake8
      run: flake8 . --ignore=E203,E302,E305,E501,E701,W503

    - name: Test with pytest
      run: xvfb-run --auto-servernum pytest --cov=. --cov-branch --cov-report=xml --junitxml=junit.xml -o junit_family=legacy tests/

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
